before_script:
  - PATH=${PATH}:`pwd`/node_modules/.bin
  - node -v
  - npm -v
  - npm install
  - bower install
  - git submodule sync
  - git submodule init
  - git submodule update --depth 50
  - gulp build

staging:
  script:
    - gulp deploy:preview
